title: Satrajit Basu
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://sjitb.github.io

aux_links:
  Public Repositories: https://github.com/sjitb?tab=repositories
